#pragma once

namespace Luntik::Packets {
enum PacketType {
  C2S_CHUNK_PACKET,
  S2C_CHUNK_PACKET,

  S2C_PLAYER_ID_PACKET,

  S2C_PLAYERS_INFO_PACKET,
  S2C_PLAYER_DISCONNECTED_PACKET,
  S2C_PLAYERS_POSITION_PACKET,

  C2S_POSITION_PACKET,
};
}
